name: sentosa
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pandas
  - numpy
  - fastapi
  - uvicorn
  - pytest
  - requests
  - scikit-learn
  - pyarrow
  - streamlit
  - httpx
  - pip
  - pip:
    - transformers
    - datasets
    - accelerate
    - torch
    - pydantic>=2.0.0
